name: Schoonheidsinstituut Katleen
favicon: null
layout_spectrum: 0.24383136187680066
typography_spectrum: 0.1440068942029029
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fb97e0'
    - '#222222'
    - '#9c638c'
    - '#929292'
    - '#eaeaea'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.7730482374317944
purpose: []
