name: Schoonheidsinstituut Katleen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fb97e0'
    - '#222222'
    - '#9c638c'
    - '#929292'
    - '#eaeaea'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
