name: Schoonheidsinstituut Katleen
favicon: null
layout_spectrum: 0.82273
typography_spectrum: 0.51848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#91eaf0'
    - '#1db4cf'
    - '#0a769a'
    - '#001a2b'
    - '#4f9a9d'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
